import type { CallResult } from "../domain/constants/statuses";

export type PilotSeedCandidate = {
  name: string;
  currentClass: string;
  status: CallResult;
};

export const PILOT_SEED_CANDIDATES: PilotSeedCandidate[] = [
  { name: "Ada Yılmaz", currentClass: "5. Sınıf", status: "reached" },
  { name: "Efe Demir", currentClass: "5. Sınıf", status: "not_reached" },
  { name: "Zeynep Kaya", currentClass: "5. Sınıf", status: "appointment" },
  { name: "Mert Arslan", currentClass: "5. Sınıf", status: "call_later" },
  { name: "Elif Çelik", currentClass: "5. Sınıf", status: "wrong_number" },
  { name: "Deniz Şahin", currentClass: "5. Sınıf", status: "reached" },
  { name: "Kerem Aydın", currentClass: "5. Sınıf", status: "not_reached" },
  { name: "İrem Koç", currentClass: "5. Sınıf", status: "appointment" },
  { name: "Bora Aksoy", currentClass: "5. Sınıf", status: "call_later" },
  { name: "Mina Özkan", currentClass: "5. Sınıf", status: "reached" },
  { name: "Ali Eren", currentClass: "6. Sınıf", status: "not_reached" },
  { name: "Duru Yıldız", currentClass: "6. Sınıf", status: "reached" },
  { name: "Kaan Polat", currentClass: "6. Sınıf", status: "appointment" },
  { name: "Nehir Aslan", currentClass: "6. Sınıf", status: "call_later" },
  { name: "Arda Kılıç", currentClass: "6. Sınıf", status: "wrong_number" },
  { name: "Eylül Taş", currentClass: "6. Sınıf", status: "reached" },
  { name: "Caner Kurt", currentClass: "6. Sınıf", status: "not_reached" },
  { name: "Lina Acar", currentClass: "6. Sınıf", status: "appointment" },
  { name: "Toprak Güneş", currentClass: "6. Sınıf", status: "call_later" },
  { name: "Melis Uçar", currentClass: "6. Sınıf", status: "reached" },
  { name: "Yağız Yalçın", currentClass: "7. Sınıf", status: "reached" },
  { name: "Selin Kaplan", currentClass: "7. Sınıf", status: "not_reached" },
  { name: "Emirhan Bozkurt", currentClass: "7. Sınıf", status: "appointment" },
  { name: "Defne Eren", currentClass: "7. Sınıf", status: "call_later" },
  { name: "Ozan Karaca", currentClass: "7. Sınıf", status: "wrong_number" },
  { name: "Asya Bulut", currentClass: "7. Sınıf", status: "reached" },
  { name: "Kuzey Can", currentClass: "7. Sınıf", status: "not_reached" },
  { name: "Ece Turan", currentClass: "7. Sınıf", status: "appointment" },
  { name: "Doruk Sezer", currentClass: "7. Sınıf", status: "call_later" },
  { name: "Nilay Çetin", currentClass: "7. Sınıf", status: "reached" },
  { name: "Rüzgar Ateş", currentClass: "7. Sınıf", status: "not_reached" },
  { name: "Sude Ersoy", currentClass: "7. Sınıf", status: "appointment" },
  { name: "Berkay Şimşek", currentClass: "8. Sınıf", status: "reached" },
  { name: "Ceren Duman", currentClass: "8. Sınıf", status: "not_reached" },
  { name: "Onur Yavuz", currentClass: "8. Sınıf", status: "appointment" },
  { name: "Azra Çakır", currentClass: "8. Sınıf", status: "call_later" },
  { name: "Alp Ekinci", currentClass: "8. Sınıf", status: "wrong_number" },
  { name: "Nisa Korkmaz", currentClass: "8. Sınıf", status: "reached" },
  { name: "Ege Sarı", currentClass: "8. Sınıf", status: "not_reached" },
  { name: "Beren Doğan", currentClass: "8. Sınıf", status: "appointment" },
  { name: "Yiğit Avcı", currentClass: "8. Sınıf", status: "call_later" },
  { name: "İdil Tekin", currentClass: "8. Sınıf", status: "reached" },
  { name: "Mete Çoban", currentClass: "8. Sınıf", status: "not_reached" },
  { name: "Lara Kılıçarslan", currentClass: "8. Sınıf", status: "appointment" },
  { name: "Baran Ay", currentClass: "8. Sınıf", status: "call_later" },
  { name: "Simay Yüce", currentClass: "8. Sınıf", status: "reached" },
  { name: "Tolga Başar", currentClass: "8. Sınıf", status: "wrong_number" },
  { name: "Dila Aksu", currentClass: "8. Sınıf", status: "not_reached" },
  { name: "Eren Tuna", currentClass: "8. Sınıf", status: "appointment" },
  { name: "Mira Bayraktar", currentClass: "8. Sınıf", status: "reached" },
  { name: "LGS Adayı Alp Arda", currentClass: "LGS", status: "reached" },
  { name: "LGS Adayı İpek Naz", currentClass: "LGS", status: "not_reached" },
  { name: "LGS Adayı Emir Can", currentClass: "LGS", status: "appointment" },
  { name: "LGS Adayı Zümra", currentClass: "LGS", status: "call_later" },
  { name: "LGS Adayı Batu", currentClass: "LGS", status: "wrong_number" },
  { name: "LGS Adayı Ela", currentClass: "LGS", status: "reached" },
  { name: "LGS Adayı Arın", currentClass: "LGS", status: "not_reached" },
  { name: "LGS Adayı Buse", currentClass: "LGS", status: "appointment" },
  { name: "LGS Adayı Kerim", currentClass: "LGS", status: "call_later" },
  { name: "LGS Adayı Nazlı", currentClass: "LGS", status: "reached" },
  { name: "YKS Adayı Ecrin", currentClass: "YKS", status: "reached" },
  { name: "YKS Adayı Furkan", currentClass: "YKS", status: "not_reached" },
  { name: "YKS Adayı Sıla", currentClass: "YKS", status: "appointment" },
  { name: "YKS Adayı Aras", currentClass: "YKS", status: "call_later" },
  { name: "YKS Adayı Elvan", currentClass: "YKS", status: "wrong_number" },
  { name: "YKS Adayı Mertcan", currentClass: "YKS", status: "reached" },
  { name: "YKS Adayı Damla", currentClass: "YKS", status: "not_reached" },
  { name: "YKS Adayı Kıvanç", currentClass: "YKS", status: "appointment" },
  { name: "YKS Adayı İlayda", currentClass: "YKS", status: "call_later" },
  { name: "YKS Adayı Deniz", currentClass: "YKS", status: "reached" }
];
